### ISSUE TITLE
how about dubbox

### ISSUE THREAD

**Issue by zhangchaoxu** [ourbeehive/Zeus#1]
我听个人说起过他们基于dubbox在做restful api，主要目的是给app和web做通用接口，当时听着这玩意用起来真心累。在用户访问量和业务复杂度没上来之前，完全没必要挖这个坑。

还有担心两点
1 将内部逻辑相对更直接的暴露给终端用户，会不会有安全隐患。
2 用dubbo做调度管理和内部bus，一旦和子模块之间存在兼容性问题，解决起来会不会很麻烦。

`再续一秒`

**Comment by johnabyss** [comment]
1.dubbo接口并不直接暴露给终端用户，你所描述的场景，我的猜想可能就是两个不同Controller调用同一 个dubbo服务，用不同的参数作为区分
2.consumer和provider需要共用协议，实际也就是java的接口类，通常来说代码层面不会存在兼容问题，至于业务逻辑的兼容性并不是dubbo所能解决
3.关于要不要上dubbo，在服务逻辑相对单一，和应用系统不多的情况下，dubbo是显得比较多余，但多数情况下，我们的应用都需要切分，应用之间会有通讯，也会存在很多重复的逻辑，使用dubbo会大大减少配置量和程序代码，所以我觉得大多数情况下是一定要上的~
